use crate::response::{UUID_TYPE, discover_rowset_envelope};

const SCHEMA_ROW_FIELDS: &str = r#"                <xsd:element sql:field="SchemaName" name="SchemaName" type="xsd:string"/>
                <xsd:element sql:field="SchemaGuid" name="SchemaGuid" type="uuid" minOccurs="0"/>
                <xsd:element sql:field="Restrictions" name="Restrictions" minOccurs="0" maxOccurs="unbounded">
                  <xsd:complexType>
                    <xsd:sequence>
                      <xsd:element sql:field="Name" name="Name" type="xsd:string" minOccurs="0"/>
                      <xsd:element sql:field="Type" name="Type" type="xsd:string" minOccurs="0"/>
                    </xsd:sequence>
                  </xsd:complexType>
                </xsd:element>
                <xsd:element sql:field="RestrictionsMask" name="RestrictionsMask" type="xsd:unsignedLong" minOccurs="0"/>"#;

const SCHEMA_ROWSET_DATA: &str = r#"          <row>
            <SchemaName>DBSCHEMA_CATALOGS</SchemaName>
            <SchemaGuid>C8B52211-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DBSCHEMA_TABLES</SchemaName>
            <SchemaGuid>C8B52229-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>TABLE_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_OLAP_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DBSCHEMA_COLUMNS</SchemaName>
            <SchemaGuid>C8B52214-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>TABLE_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TABLE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>COLUMN_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>COLUMN_OLAP_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DBSCHEMA_PROVIDER_TYPES</SchemaName>
            <SchemaGuid>C8B5222C-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>DATA_TYPE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>BEST_MATCH</Name><Type>xsd:boolean</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_CUBES</SchemaName>
            <SchemaGuid>C8B522D8-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>BASE_CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_DIMENSIONS</SchemaName>
            <SchemaGuid>C8B522D9-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>DIMENSION_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>127</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_HIERARCHIES</SchemaName>
            <SchemaGuid>C8B522DA-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_ORIGIN</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>511</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_LEVELS</SchemaName>
            <SchemaGuid>C8B522DB-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_ORIGIN</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>LEVEL_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>1023</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_MEASURES</SchemaName>
            <SchemaGuid>C8B522DC-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEASURE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEASURE_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEASUREGROUP_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>MEASURE_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>255</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_PROPERTIES</SchemaName>
            <SchemaGuid>C8B522DD-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEMBER_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>PROPERTY_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>PROPERTY_TYPE</Name><Type>xsd:short</Type></Restrictions>
            <Restrictions><Name>PROPERTY_CONTENT_TYPE</Name><Type>xsd:short</Type></Restrictions>
            <Restrictions><Name>PROPERTY_ORIGIN</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>PROPERTY_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>8191</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_MEMBERS</SchemaName>
            <SchemaGuid>C8B522DE-5CF3-11CE-ADE5-00AA0044773D</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LEVEL_NUMBER</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <Restrictions><Name>MEMBER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEMBER_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEMBER_CAPTION</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEMBER_TYPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>TREE_OP</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>SCOPE</Name><Type>xsd:int</Type></Restrictions>
            <RestrictionsMask>16383</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_FUNCTIONS</SchemaName>
            <SchemaGuid>A07CCD07-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>LIBRARY_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>INTERFACE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>FUNCTION_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ORIGIN</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_ACTIONS</SchemaName>
            <SchemaGuid>A07CCD08-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ACTION_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ACTION_TYPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>COORDINATE</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>COORDINATE_TYPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>INVOCATION</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>511</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_SETS</SchemaName>
            <SchemaGuid>A07CCD0B-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SET_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCOPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>HIERARCHY_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>SET_EVALUATION_CONTEXT</Name><Type>xsd:int</Type></Restrictions>
            <RestrictionsMask>255</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_INSTANCES</SchemaName>
            <SchemaGuid>20518699-2474-4C15-9885-0E947EC7A7E3</SchemaGuid>
            <Restrictions><Name>INSTANCE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_KPIS</SchemaName>
            <SchemaGuid>2AE44109-ED3D-4842-B16F-B694D1CB0E3F</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>KPI_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_SOURCE</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <Restrictions><Name>SCOPE</Name><Type>xsd:int</Type></Restrictions>
            <RestrictionsMask>63</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_MEASUREGROUPS</SchemaName>
            <SchemaGuid>E1625EBF-FA96-42FD-BEA6-DB90ADAFD96B</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEASUREGROUP_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_MEASUREGROUP_DIMENSIONS</SchemaName>
            <SchemaGuid>A07CCD33-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CUBE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MEASUREGROUP_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DIMENSION_VISIBILITY</Name><Type>xsd:unsignedShort</Type></Restrictions>
            <RestrictionsMask>63</RestrictionsMask>
          </row>
          <row>
            <SchemaName>MDSCHEMA_INPUT_DATASOURCES</SchemaName>
            <SchemaGuid>A07CCD32-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SCHEMA_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DATASOURCE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DATASOURCE_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_SERVICES</SchemaName>
            <SchemaGuid>3ADD8A95-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>SERVICE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SERVICE_TYPE_ID</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_SERVICE_PARAMETERS</SchemaName>
            <SchemaGuid>3ADD8A75-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>SERVICE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>PARAMETER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_FUNCTIONS</SchemaName>
            <SchemaGuid>3ADD8A79-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>SERVICE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>FUNCTION_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_MODEL_CONTENT</SchemaName>
            <SchemaGuid>3ADD8A76-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>MODEL_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ATTRIBUTE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>NODE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>NODE_UNIQUE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>NODE_TYPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>NODE_GUID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>NODE_CAPTION</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TREE_OPERATION</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <RestrictionsMask>1023</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_MODEL_XML</SchemaName>
            <SchemaGuid>4290B2D5-0E9C-4AA7-9369-98C95CFD9D13</SchemaGuid>
            <Restrictions><Name>MODEL_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_MODEL_CONTENT_PMML</SchemaName>
            <SchemaGuid>4290B2D5-0E9C-4AA7-9369-98C95CFD9D13</SchemaGuid>
            <Restrictions><Name>MODEL_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_MODELS</SchemaName>
            <SchemaGuid>3ADD8A77-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>MODEL_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SERVICE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SERVICE_TYPE_ID</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <Restrictions><Name>MINING_STRUCTURE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>127</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_COLUMNS</SchemaName>
            <SchemaGuid>3ADD8A78-D8B9-11D2-8D2A-00E029154FDE</SchemaGuid>
            <Restrictions><Name>MODEL_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MODEL_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>COLUMN_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_STRUCTURES</SchemaName>
            <SchemaGuid>883269F3-0CAD-462F-B6F5-E88A72418C4B</SchemaGuid>
            <Restrictions><Name>STRUCTURE_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>STRUCTURE_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>STRUCTURE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>7</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DMSCHEMA_MINING_STRUCTURE_COLUMNS</SchemaName>
            <SchemaGuid>9952E836-BFBF-4D1F-8535-9B67DBD9DDFE</SchemaGuid>
            <Restrictions><Name>STRUCTURE_CATALOG</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>STRUCTURE_SCHEMA</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>STRUCTURE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>COLUMN_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_DATASOURCES</SchemaName>
            <SchemaGuid>06C03D41-F66D-49F3-B1B8-987F7AF4CF18</SchemaGuid>
            <Restrictions><Name>DataSourceName</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>URL</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ProviderName</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ProviderType</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>AuthenticationMode</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_PROPERTIES</SchemaName>
            <SchemaGuid>4B40ADFB-8B09-4758-97BB-636E8AE97BCF</SchemaGuid>
            <Restrictions><Name>PropertyName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_SCHEMA_ROWSETS</SchemaName>
            <SchemaGuid>EEA0302B-7922-4992-8991-0E605D0E5593</SchemaGuid>
            <Restrictions><Name>SchemaName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_ENUMERATORS</SchemaName>
            <SchemaGuid>55A9E78B-ACCB-45B4-95A6-94C5065617A7</SchemaGuid>
            <Restrictions><Name>EnumName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_KEYWORDS</SchemaName>
            <SchemaGuid>1426C443-4CDD-4A40-8F45-572FAB9BBAA1</SchemaGuid>
            <Restrictions><Name>Keyword</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_LITERALS</SchemaName>
            <SchemaGuid>C3EF5ECB-0A07-4665-A140-B075722DBDC2</SchemaGuid>
            <Restrictions><Name>LiteralName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XML_METADATA</SchemaName>
            <SchemaGuid>3444B255-171E-4CB9-AD98-19E57888A75F</SchemaGuid>
            <Restrictions><Name>DatabaseID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DimensionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CubeID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MeasureGroupID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>PartitionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>PerspectiveID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DimensionPermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>RoleID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DatabasePermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MiningModelID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MiningModelPermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DataSourceID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MiningStructureID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>AggregationDesignID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TraceID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MiningStructurePermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CubePermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>AssemblyID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>MdxScriptID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DataSourceViewID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DataSourcePermissionID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CalculatedColumns</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ObjectExpansion</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>DBWorkloadGroupID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ResourcePoolID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ModifiedAfter</Name><Type>xsd:dateTime</Type></Restrictions>
            <RestrictionsMask>67108863</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_TRACES</SchemaName>
            <SchemaGuid>A07CCD1A-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>TraceID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>Type</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_TRACE_DEFINITION_PROVIDERINFO</SchemaName>
            <SchemaGuid>A07CCD1B-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>Data</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XEVENT_PACKAGES</SchemaName>
            <SchemaGuid>A07CCD1C-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>ID</Name><Type>uuid</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XEVENT_OBJECTS</SchemaName>
            <SchemaGuid>A07CCD1D-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>OBJECT_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XEVENT_OBJECT_COLUMNS</SchemaName>
            <SchemaGuid>A07CCD1E-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>OBJECT_NAME</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XEVENT_SESSION_TARGETS</SchemaName>
            <SchemaGuid>A07CCD1F-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>XESessionName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_XEVENT_SESSIONS</SchemaName>
            <SchemaGuid>A07CCD20-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>XESessionName</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_TRACE_COLUMNS</SchemaName>
            <SchemaGuid>A07CCD18-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>Data</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_TRACE_EVENT_CATEGORIES</SchemaName>
            <SchemaGuid>A07CCD19-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>Data</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_MEMORYUSAGE</SchemaName>
            <SchemaGuid>A07CCD21-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>SPID</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <Restrictions><Name>MemoryUsed</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>BaseObjectType</Name><Type>xsd:unsignedInt</Type></Restrictions>
            <Restrictions><Name>Shrinkable</Name><Type>xsd:boolean</Type></Restrictions>
            <RestrictionsMask>15</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_MEMORYGRANT</SchemaName>
            <SchemaGuid>A07CCD23-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>SPID</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_LOCKS</SchemaName>
            <SchemaGuid>A07CCD24-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>SPID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>LOCK_TRANSACTION_ID</Name><Type>uuid</Type></Restrictions>
            <Restrictions><Name>LOCK_OBJECT_ID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>LOCK_STATUS</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>LOCK_TYPE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>LOCK_MIN_TOTAL_MS</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>63</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_CONNECTIONS</SchemaName>
            <SchemaGuid>A07CCD25-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CONNECTION_ID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CONNECTION_USER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CONNECTION_IMPERSONATED_USER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CONNECTION_HOST_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CONNECTION_ELAPSED_TIME_MS</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>CONNECTION_LAST_COMMAND_ELAPSED_TIME_MS</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>CONNECTION_IDLE_TIME_MS</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>127</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_SESSIONS</SchemaName>
            <SchemaGuid>A07CCD26-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>SESSION_ID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SESSION_SPID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>SESSION_CONNECTION_ID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>SESSION_USER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SESSION_CURRENT_DATABASE</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>SESSION_ELAPSED_TIME_MS</Name><Type>xsd:unsignedLong</Type></Restrictions>
            <Restrictions><Name>SESSION_CPU_TIME_MS</Name><Type>xsd:unsignedLong</Type></Restrictions>
            <Restrictions><Name>SESSION_IDLE_TIME_MS</Name><Type>xsd:unsignedLong</Type></Restrictions>
            <Restrictions><Name>SESSION_STATUS</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>RESTRICT_CATALOG_ID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>REQUEST_ACTIVITY_ID</Name><Type>uuid</Type></Restrictions>
            <Restrictions><Name>CLIENT_ACTIVITY_ID</Name><Type>uuid</Type></Restrictions>
            <RestrictionsMask>4095</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_JOBS</SchemaName>
            <SchemaGuid>A07CCD27-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>SPID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>JOB_ID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>JOB_DESCRIPTION</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>JOB_THREADPOOL_ID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>JOB_MIN_TOTAL_TIME_MS</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_TRANSACTIONS</SchemaName>
            <SchemaGuid>A07CCD28-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>TRANSACTION_ID</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>TRANSACTION_SESSION_ID</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_DB_CONNECTIONS</SchemaName>
            <SchemaGuid>A07CCD2A-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>CONNECTION_ID</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CONNECTION_IN_USE</Name><Type>xsd:int</Type></Restrictions>
            <Restrictions><Name>CONNECTION_SERVER_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CONNECTION_CATALOG_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>CONNECTION_SPID</Name><Type>xsd:int</Type></Restrictions>
            <RestrictionsMask>31</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_MASTER_KEY</SchemaName>
            <SchemaGuid>A07CCD29-8148-11D0-87BB-00C04FC33942</SchemaGuid>
            <Restrictions><Name>KEY</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_MODEL</SchemaName>
            <SchemaGuid>F1B5C3AB-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_TABLES</SchemaName>
            <SchemaGuid>F1B5C3AC-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>Name</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_COLUMNS</SchemaName>
            <SchemaGuid>F1B5C3AD-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>TableID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_MEASURES</SchemaName>
            <SchemaGuid>F1B5C3AE-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>TableID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_HIERARCHIES</SchemaName>
            <SchemaGuid>F1B5C3AF-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>TableID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_LEVELS</SchemaName>
            <SchemaGuid>F1B5C3B0-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>HierarchyID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_RELATIONSHIPS</SchemaName>
            <SchemaGuid>F1B5C3B1-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>1</RestrictionsMask>
          </row>
          <row>
            <SchemaName>TMSCHEMA_PARTITIONS</SchemaName>
            <SchemaGuid>F1B5C3B2-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>ID</Name><Type>xsd:long</Type></Restrictions>
            <Restrictions><Name>TableID</Name><Type>xsd:long</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
          <row>
            <SchemaName>DISCOVER_CALC_DEPENDENCY</SchemaName>
            <SchemaGuid>F1B5C3B3-7CD1-4F77-89A8-9DE3D0C9DBC0</SchemaGuid>
            <Restrictions><Name>DATABASE_NAME</Name><Type>xsd:string</Type></Restrictions>
            <Restrictions><Name>OBJECT_TYPE</Name><Type>xsd:string</Type></Restrictions>
            <RestrictionsMask>3</RestrictionsMask>
          </row>
"#;

pub fn get_schemas_response() -> String {
    discover_rowset_envelope(UUID_TYPE, SCHEMA_ROW_FIELDS, SCHEMA_ROWSET_DATA)
}
