// Shared MDX string constants used by both unit tests and benchmarks.

pub const MDX_CCHILDREN_LEAF: &str = "WITH MEMBER [Measures].cChildren As 'AddCalculatedMembers([ProductCategory].[ProductCategory].currentmember.children).count' Set FilteredMembers As '{[ProductCategory].[ProductCategory].&[Category B]}' Select {[Measures].cChildren} on ROWS, Hierarchize(Generate(FilteredMembers, Ascendants([ProductCategory].[ProductCategory].currentmember))) DIMENSION PROPERTIES PARENT_UNIQUE_NAME, MEMBER_TYPE ON COLUMNS FROM [Model]";

pub const MDX_CCHILDREN_MEASURE: &str = "WITH MEMBER [Measures].cChildren As 'AddCalculatedMembers([Measures].currentmember.children).count' Set FilteredMembers As '{[Measures].[Total Sales]}' Select {[Measures].cChildren} on ROWS, Hierarchize(Generate(FilteredMembers, Ascendants([Measures].currentmember))) ON COLUMNS FROM [Model]";

pub const MDX_ALL_MEMBERS: &str = "SELECT {AddCalculatedMembers({[ProductCategory].[ProductCategory].[(All)].Members})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Model] CELL PROPERTIES CELL_ORDINAL";

pub const MDX_ALL_CHILDREN: &str = "SELECT {AddCalculatedMembers({[ProductCategory].[ProductCategory].[All].Children})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Model] CELL PROPERTIES CELL_ORDINAL";

pub const MDX_DRILLDOWN: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[ProductCategory].[ProductCategory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_SLICER: &str = "SELECT  FROM [Model] WHERE ([ProductCategory].[ProductCategory].&[Category A],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_SLICER_ALL: &str = "SELECT  FROM [Model] WHERE ([ProductCategory].[ProductCategory].[All],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_SUBQUERY_FILTERS: &str = "SELECT FROM (SELECT ({[ProductCategory].[ProductCategory].&[Category A],[ProductCategory].[ProductCategory].&[Category C]}) ON COLUMNS FROM [Model]) WHERE ([Measures].[Total Sales])";

pub const MDX_REGION_SLICER: &str = "SELECT  FROM [Model] WHERE ([Region].[Region].&[North],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_REGION_DRILLDOWN: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Region].[Region].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_CAPTION,[Region].[Region].[Region]MEMBER_NAME,[Region].[Region].[Region]MEMBER_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_KEY,[Region].[Region].[Region]MEMBER_TYPE,[Region].[Region].[Region]MEMBER_VALUE,[Region].[Region].[Region]LEVEL_NUMBER,[Region].[Region].[Region]LEVEL_UNIQUE_NAME,[Region].[Region].[Region]PARENT_LEVEL,[Region].[Region].[Region]PARENT_UNIQUE_NAME,[Region].[Region].[Region]PARENT_COUNT,[Region].[Region].[Region]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_REGION_ALL_MEMBERS: &str = "SELECT {AddCalculatedMembers({[Region].[Region].[(All)].Members})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Model] CELL PROPERTIES CELL_ORDINAL";

pub const MDX_REGION_SLICER_ALL: &str = "SELECT  FROM [Model] WHERE ([Region].[Region].[All],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_KAT_ROWS_REGION_FILTER: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[ProductCategory].[ProductCategory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Region].[Region].&[North],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_KAT_ROWS_REGION_ALL: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[ProductCategory].[ProductCategory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Region].[Region].[All],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_CROSSJOIN_PROBE: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[ProductCategory].[ProductCategory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Region].[Region].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_CAPTION,[Region].[Region].[Region]MEMBER_NAME,[Region].[Region].[Region]MEMBER_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_KEY,[Region].[Region].[Region]MEMBER_TYPE,[Region].[Region].[Region]MEMBER_VALUE,[Region].[Region].[Region]LEVEL_NUMBER,[Region].[Region].[Region]LEVEL_UNIQUE_NAME,[Region].[Region].[Region]PARENT_LEVEL,[Region].[Region].[Region]PARENT_UNIQUE_NAME,[Region].[Region].[Region]PARENT_COUNT,[Region].[Region].[Region]CHILDREN_CARDINALITY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_KAT_FILTERED_SINGLE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[ProductCategory].[ProductCategory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM (SELECT ({[ProductCategory].[ProductCategory].&[Category B]}) ON COLUMNS  FROM [Model]) WHERE ([Region].[Region].[All],[Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_NESTED_BOTH_FILTERS: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Region].[Region].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_CAPTION,[Region].[Region].[Region]MEMBER_NAME,[Region].[Region].[Region]MEMBER_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_KEY,[Region].[Region].[Region]MEMBER_TYPE,[Region].[Region].[Region]MEMBER_VALUE,[Region].[Region].[Region]LEVEL_NUMBER,[Region].[Region].[Region]LEVEL_UNIQUE_NAME,[Region].[Region].[Region]PARENT_LEVEL,[Region].[Region].[Region]PARENT_UNIQUE_NAME,[Region].[Region].[Region]PARENT_COUNT,[Region].[Region].[Region]CHILDREN_CARDINALITY ON COLUMNS  FROM (SELECT ({[Region].[Region].&[North]}) ON COLUMNS  FROM (SELECT ({[ProductCategory].[ProductCategory].&[Category A],[ProductCategory].[ProductCategory].&[Category B],[ProductCategory].[ProductCategory].&[Category D]}) ON COLUMNS  FROM [Model])) WHERE ([Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_DRILLDOWN_MEMBER_COLLAPSE: &str = "SELECT NON EMPTY Hierarchize(DrilldownMember(CrossJoin({[ProductCategory].[ProductCategory].[All],[ProductCategory].[ProductCategory].[ProductCategory].AllMembers}, {([Region].[Region].[All])}), {-{[ProductCategory].[ProductCategory].&[Category A]}}, [Region].[Region])) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_CAPTION,[Region].[Region].[Region]MEMBER_NAME,[Region].[Region].[Region]MEMBER_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_KEY,[Region].[Region].[Region]MEMBER_TYPE,[Region].[Region].[Region]MEMBER_VALUE,[Region].[Region].[Region]LEVEL_NUMBER,[Region].[Region].[Region]LEVEL_UNIQUE_NAME,[Region].[Region].[Region]PARENT_LEVEL,[Region].[Region].[Region]PARENT_UNIQUE_NAME,[Region].[Region].[Region]PARENT_COUNT,[Region].[Region].[Region]CHILDREN_CARDINALITY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const MDX_DRILLDOWN_MEMBER_COLLAPSE_PRODUCT: &str = "SELECT NON EMPTY Hierarchize(DrilldownMember(CrossJoin({[Region].[Region].[All],[Region].[Region].[Region].AllMembers}, {([ProductCategory].[ProductCategory].[All])}), {-{[ProductCategory].[ProductCategory].&[Category D]}}, [ProductCategory].[ProductCategory])) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_CAPTION,[Region].[Region].[Region]MEMBER_NAME,[Region].[Region].[Region]MEMBER_UNIQUE_NAME,[Region].[Region].[Region]MEMBER_KEY,[Region].[Region].[Region]MEMBER_TYPE,[Region].[Region].[Region]MEMBER_VALUE,[Region].[Region].[Region]LEVEL_NUMBER,[Region].[Region].[Region]LEVEL_UNIQUE_NAME,[Region].[Region].[Region]PARENT_LEVEL,[Region].[Region].[Region]PARENT_UNIQUE_NAME,[Region].[Region].[Region]PARENT_COUNT,[Region].[Region].[Region]CHILDREN_CARDINALITY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_CAPTION,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_KEY,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_TYPE,[ProductCategory].[ProductCategory].[ProductCategory]MEMBER_VALUE,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_NUMBER,[ProductCategory].[ProductCategory].[ProductCategory]LEVEL_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_LEVEL,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_UNIQUE_NAME,[ProductCategory].[ProductCategory].[ProductCategory]PARENT_COUNT,[ProductCategory].[ProductCategory].[ProductCategory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Measures].[Total Sales]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

// Two off-axis leaf filters + two-row-dim + Units (project3 crash reproducer).
pub const MDX_TWO_LEAF_FILTERS_UNITS: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Segment].[Segment].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Segment].[Segment].[Segment]MEMBER_CAPTION,[Segment].[Segment].[Segment]MEMBER_NAME,[Segment].[Segment].[Segment]MEMBER_UNIQUE_NAME,[Segment].[Segment].[Segment]MEMBER_KEY,[Segment].[Segment].[Segment]MEMBER_TYPE,[Segment].[Segment].[Segment]MEMBER_VALUE,[Segment].[Segment].[Segment]LEVEL_NUMBER,[Segment].[Segment].[Segment]LEVEL_UNIQUE_NAME,[Segment].[Segment].[Segment]PARENT_LEVEL,[Segment].[Segment].[Segment]PARENT_UNIQUE_NAME,[Segment].[Segment].[Segment]PARENT_COUNT,[Segment].[Segment].[Segment]CHILDREN_CARDINALITY,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Model] WHERE ([Category].[Category].&[Food],[Channel].[Channel].&[Wholesale],[Measures].[Units]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

// Unique ExecuteStatement MDX shapes captured from a real Excel session
// against the restored project3 demo.
pub const EXCEL_TRACE_TOTAL_REVENUE: &str = "SELECT  FROM [Sales] WHERE ([Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_DRILLDOWN_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_MEMBERS: &str = "SELECT {AddCalculatedMembers({[Territory].[Territory].[Territory].Members})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Sales] CELL PROPERTIES CELL_ORDINAL";

pub const EXCEL_TRACE_TERRITORY_FILTER_NORTHWEST_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM (SELECT ({[Territory].[Territory].&[Northwest]}) ON COLUMNS  FROM [Sales]) WHERE ([Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_ALL_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].[All],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_ALL_MEMBERS: &str = "SELECT {AddCalculatedMembers({[Segment].[Segment].[(All)].Members})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Sales] CELL PROPERTIES CELL_ORDINAL";

pub const EXCEL_TRACE_SEGMENT_ALL_CHILDREN: &str = "SELECT {AddCalculatedMembers({[Segment].[Segment].[All].Children})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Sales] CELL PROPERTIES CELL_ORDINAL";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_FILTER_SOUTH_SEGMENT_CONSUMER_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM (SELECT ({[Territory].[Territory].&[South]}) ON COLUMNS  FROM [Sales]) WHERE ([Segment].[Segment].&[Consumer],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_ALL_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].[All],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_CHANNEL_ALL_MEMBERS: &str = "SELECT {AddCalculatedMembers({[Channel].[Channel].[(All)].Members})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Sales] CELL PROPERTIES CELL_ORDINAL";

pub const EXCEL_TRACE_CHANNEL_ALL_CHILDREN: &str = "SELECT {AddCalculatedMembers({[Channel].[Channel].[All].Children})} DIMENSION PROPERTIES MEMBER_TYPE ON COLUMNS FROM [Sales] CELL PROPERTIES CELL_ORDINAL";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_REVENUE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_DEFAULT_MEASURE: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_UNITS: &str = "SELECT NON EMPTY Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Units]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_REVENUE: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_CATEGORY_TERRITORY_REVENUE: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_COLLAPSE_NORTHWEST_REVENUE: &str = "SELECT NON EMPTY Hierarchize(DrilldownMember(CrossJoin({[Territory].[Territory].[All],[Territory].[Territory].[Territory].AllMembers}, {([Category].[Category].[All])}), {-{[Territory].[Territory].&[Northwest]}}, [Category].[Category])) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Revenue]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_DEFAULT_MEASURE: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_UNITS: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].&[Wholesale],[Measures].[Units]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_CHANNEL_WHOLESALE_CCHILDREN: &str = "WITH MEMBER [Measures].cChildren As 'AddCalculatedMembers([Channel].[Channel].currentmember.children).count' Set FilteredMembers As '{[Channel].[Channel].&[Wholesale]}' Select {[Measures].cChildren} on ROWS, Hierarchize(Generate(FilteredMembers, Ascendants([Channel].[Channel].currentmember))) DIMENSION PROPERTIES PARENT_UNIQUE_NAME, MEMBER_TYPE ON COLUMNS FROM [Sales]";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_CONSUMER_UNITS: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].&[Consumer],[Channel].[Channel].[All],[Measures].[Units]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_SEGMENT_CONSUMER_CCHILDREN: &str = "WITH MEMBER [Measures].cChildren As 'AddCalculatedMembers([Segment].[Segment].currentmember.children).count' Set FilteredMembers As '{[Segment].[Segment].&[Consumer]}' Select {[Measures].cChildren} on ROWS, Hierarchize(Generate(FilteredMembers, Ascendants([Segment].[Segment].currentmember))) DIMENSION PROPERTIES PARENT_UNIQUE_NAME, MEMBER_TYPE ON COLUMNS FROM [Sales]";

pub const EXCEL_TRACE_TERRITORY_CATEGORY_ALL_UNITS: &str = "SELECT NON EMPTY CrossJoin(Hierarchize({DrilldownLevel({[Territory].[Territory].[All]},,,INCLUDE_CALC_MEMBERS)}), Hierarchize({DrilldownLevel({[Category].[Category].[All]},,,INCLUDE_CALC_MEMBERS)})) DIMENSION PROPERTIES PARENT_UNIQUE_NAME,HIERARCHY_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_CAPTION,[Territory].[Territory].[Territory]MEMBER_NAME,[Territory].[Territory].[Territory]MEMBER_UNIQUE_NAME,[Territory].[Territory].[Territory]MEMBER_KEY,[Territory].[Territory].[Territory]MEMBER_TYPE,[Territory].[Territory].[Territory]MEMBER_VALUE,[Territory].[Territory].[Territory]LEVEL_NUMBER,[Territory].[Territory].[Territory]LEVEL_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_LEVEL,[Territory].[Territory].[Territory]PARENT_UNIQUE_NAME,[Territory].[Territory].[Territory]PARENT_COUNT,[Territory].[Territory].[Territory]CHILDREN_CARDINALITY,[Category].[Category].[Category]MEMBER_CAPTION,[Category].[Category].[Category]MEMBER_NAME,[Category].[Category].[Category]MEMBER_UNIQUE_NAME,[Category].[Category].[Category]MEMBER_KEY,[Category].[Category].[Category]MEMBER_TYPE,[Category].[Category].[Category]MEMBER_VALUE,[Category].[Category].[Category]LEVEL_NUMBER,[Category].[Category].[Category]LEVEL_UNIQUE_NAME,[Category].[Category].[Category]PARENT_LEVEL,[Category].[Category].[Category]PARENT_UNIQUE_NAME,[Category].[Category].[Category]PARENT_COUNT,[Category].[Category].[Category]CHILDREN_CARDINALITY ON COLUMNS  FROM [Sales] WHERE ([Segment].[Segment].[All],[Channel].[Channel].[All],[Measures].[Units]) CELL PROPERTIES VALUE, FORMAT_STRING, BACK_COLOR, FORE_COLOR";

pub const EXCEL_TRACE_PROJECT3_EXECUTES: &[&str] = &[
    EXCEL_TRACE_TOTAL_REVENUE,
    EXCEL_TRACE_TERRITORY_DRILLDOWN_REVENUE,
    EXCEL_TRACE_TERRITORY_MEMBERS,
    EXCEL_TRACE_TERRITORY_FILTER_NORTHWEST_REVENUE,
    EXCEL_TRACE_SEGMENT_ALL_REVENUE,
    EXCEL_TRACE_SEGMENT_ALL_MEMBERS,
    EXCEL_TRACE_SEGMENT_ALL_CHILDREN,
    EXCEL_TRACE_SEGMENT_CONSUMER_REVENUE,
    EXCEL_TRACE_TERRITORY_FILTER_SOUTH_SEGMENT_CONSUMER_REVENUE,
    EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_ALL_REVENUE,
    EXCEL_TRACE_CHANNEL_ALL_MEMBERS,
    EXCEL_TRACE_CHANNEL_ALL_CHILDREN,
    EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_REVENUE,
    EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_DEFAULT_MEASURE,
    EXCEL_TRACE_SEGMENT_CONSUMER_CHANNEL_WHOLESALE_UNITS,
    EXCEL_TRACE_TERRITORY_CATEGORY_REVENUE,
    EXCEL_TRACE_CATEGORY_TERRITORY_REVENUE,
    EXCEL_TRACE_TERRITORY_CATEGORY_COLLAPSE_NORTHWEST_REVENUE,
    EXCEL_TRACE_TERRITORY_CATEGORY_DEFAULT_MEASURE,
    EXCEL_TRACE_TERRITORY_CATEGORY_UNITS,
    EXCEL_TRACE_CHANNEL_WHOLESALE_CCHILDREN,
    EXCEL_TRACE_TERRITORY_CATEGORY_CONSUMER_UNITS,
    EXCEL_TRACE_SEGMENT_CONSUMER_CCHILDREN,
    EXCEL_TRACE_TERRITORY_CATEGORY_ALL_UNITS,
];
